# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/160Lu6urjC6Y_bSyEVCf8yZxL3QUnDJLO
"""

Score = input().split()
count = 0
for i in range(len(Score)):
  if int(Score[i]) < 60:
    count += 1
print(count)

